$f = 'd:\minadesign\github\antigravity\SERKAN\game\assets\index-845b001d.js'
$s = [System.IO.File]::ReadAllText($f)

# 1. Update hE.init to include mock articles in prismicCache
# This fixes the 404 on click.
$mock_data = 'const mocks=[{uid:"cat_1_l",data:{article_image:{url:"/kategori/1 sol gelinlik.png"},title:"Gelinlik - Klasik",short_desc:"Zarif ve zamansız bir gelinlik.",etek_kesimi:"A Kesim",kumas:"Fransız Danteli",url:"https://minalidya.wedding/kategori/gelinlik"}},{uid:"cat_1_r",data:{article_image:{url:"/kategori/1 sag tesettur gelinlik.png"},title:"Tesettür Gelinlik",short_desc:"Modern ve nazik tesettür tasarımı.",etek_kesimi:"Prenses",kumas:"Mikas",url:"https://minalidya.wedding/kategori/tesettur-gelinlik"}},{uid:"cat_2_l",data:{article_image:{url:"/kategori/2 sol nisanlik.png"},title:"Nişanlık - Modern",short_desc:"Özel günleriniz için modern şıklık.",etek_kesimi:"Balık",kumas:"Saten",url:"https://minalidya.wedding/kategori/nisanlik"}},{uid:"cat_2_r",data:{article_image:{url:"/kategori/2 sag kinalik.png"},title:"Kınalık - Geleneksel",short_desc:"Geleneksel motiflerle bezeli kinalık.",etek_kesimi:"Bindallı",kumas:"Kadife",url:"https://minalidya.wedding/kategori/kinalik"}},{uid:"cat_3_l",data:{article_image:{url:"/kategori/3 sol soz.png"},title:"Söz Elbisesi",short_desc:"Sade ve etkileyici bir söz elbisesi.",etek_kesimi:"Düz",kumas:"Şifon",url:"https://minalidya.wedding/kategori/soz-elbisesi"}},{uid:"cat_3_r",data:{article_image:{url:"/kategori/3 sag after.png"},title:"After Party Elbisesi",short_desc:"Eğlence dolu anlar için konforlu şıklık.",etek_kesimi:"Kısa",kumas:"Simli Kumaş",url:"https://minalidya.wedding/kategori/after-party"}},{uid:"cat_4_l",data:{article_image:{url:"/kategori/4 sol kaftan.png"},title:"Kaftan - El İşçiliği",short_desc:"Yüksek kalite el işçiliği ile üretilmiştir.",etek_kesimi:"Geleneksel",kumas:"İpek",url:"https://minalidya.wedding/kategori/kaftan"}},{uid:"cat_4_r",data:{article_image:{url:"/kategori/4 sag abiye.png"},title:"Abiye - Gece Elbisesi",short_desc:"Gecenin yıldızı olmanız için tasarlandı.",etek_kesimi:"Yırtmaçlı",kumas:"Brokar",url:"https://minalidya.wedding/kategori/abiye"}}]; mocks.forEach(m=>{this.articles.push(m);this.prismicCache[m.uid]=m});'
$old_hE_init_end = 'this.articles.forEach(n=>{this.prismicCache[n.uid]=n})'
$s = $s.Replace($old_hE_init_end, $old_hE_init_end + ';' + $mock_data)

# 2. Fix Sb class to be more robust
# Constructor: Use the patched version from before but ensure it doesn't fail if overlay is missing
$old_sb_const = 'class Sb{constructor(e,t,n){this.experience=new Rt,this.scene=this.experience.scene,this.ressources=this.experience.ressources,this.time=this.experience.time,this.ref=e,this.btn=t,this.article=n,this.overlay=document.querySelector(".details_content")}'
$new_sb_const = 'class Sb{constructor(e,t,n){this.experience=new Rt,this.scene=this.experience.scene,this.ressources=this.experience.ressources,this.time=this.experience.time,this.ref=e,this.btn=t,this.article=n,this.overlay=null}'
$s = $s.Replace($old_sb_const, $new_sb_const)

# Update: Add null checks
$old_sb_update = 'update(){if(this.btn.isOpen){this.overlay.classList.add("active");document.querySelector(".details_title").innerHTML=this.article.data.title;document.querySelector(".details_desc").innerHTML=this.article.data.short_desc;document.querySelector(".etek_value").innerHTML=this.article.data.etek_kesimi;document.querySelector(".kumas_value").innerHTML=this.article.data.kumas;document.querySelector(".details_cta").href=this.article.data.url;}else{const anyOpen=this.experience.world&&this.experience.world.page&&this.experience.world.page.btns&&this.experience.world.page.btns.some(b=>b.isOpen);if(!anyOpen)this.overlay.classList.remove("active");}}'
$new_sb_update = 'update(){if(!this.overlay)this.overlay=document.querySelector(".details_content");if(!this.overlay)return;if(this.btn.isOpen){this.overlay.classList.add("active");const t=document.querySelector(".details_title"),d=document.querySelector(".details_desc"),e=document.querySelector(".etek_value"),k=document.querySelector(".kumas_value"),c=document.querySelector(".details_cta");if(t)t.innerHTML=this.article.data.title;if(d)d.innerHTML=this.article.data.short_desc;if(e)e.innerHTML=this.article.data.etek_kesimi;if(k)k.innerHTML=this.article.data.kumas;if(c)c.href=this.article.data.url;}else{const anyOpen=this.experience.world&&this.experience.world.page&&this.experience.world.page.btns&&this.experience.world.page.btns.some(b=>b.isOpen);if(!anyOpen)this.overlay.classList.remove("active");}}'
$s = $s.Replace($old_sb_update, $new_sb_update)

[System.IO.File]::WriteAllText($f, $s)
Write-Output "Final corrective patch applied successfully."
